# These are supported funding model platforms

github: louagej
ko_fi: joblouage
liberapay: joblouage

# open_collective: # al-go-mcp-server - Transparent project funding

# Enterprise/Commercial support (when you're ready):
# tidelift: npm/al-go-mcp-server

# Specialized platforms (less common for code projects):
# patreon: # yourusername - Good if you create tutorials/content
# issuehunt: # yourusername - Bounties for specific issues
# otechie: # yourusername - 1-on-1 mentoring platform
# community_bridge: # project-name - Linux Foundation projects
# lfx_crowdfunding: # project-name - Linux Foundation crowdfunding

# Custom sponsorship URLs (if you have specific sponsors):
# custom: # ['https://your-sponsor-page.com', 'https://another-sponsor.com']